### ISSUE TITLE
Meta: wrong / misleading info

### ISSUE THREAD

**Issue by Narretz** [lpolepeddi/made-with-angular#100]
I've just checked some of the sites and two of them - godaddy.com and https://egov.maryland.gov/msp/vsi don't have any angular on the linked pages. So either the actual angular is behind a login wall, or they no longer use it. I think it would make sense to make a note if it's the second case, and make it easier to report sites that no longer use it, in the first case.

**Comment by lpolepeddi** [comment]
Hi @Narretz, thanks for raising these issues:

1. **GoDaddy.** Thanks for catching this. Looks like GoDaddy still uses Angular on their [Domain Name Search](https://www.godaddy.com/domains/domain-name-search.aspx) page, and I've updated Made with Angular with this link. Any thoughts on how to make it easier to report sites that no longer use Angular?
2. **Maryland State Police**. This site was [submitted here](https://github.com/madewithangular/madewithangular.github.io/issues/42), so I'm assuming they use Angular behind the login wall. Any thoughts for how to make this more clear?
