### ISSUE TITLE
Eureca

### ISSUE THREAD

**Issue by pfms** [lpolepeddi/made-with-angular#14]
Eureca - Web application that once was built upon BackboneJS, and now, almost 100% of it was ported to AngularJS.

A fine example of the framework capabilities, since angularJS became responsible for loading backboneJS views into the application.

https://www.eureca.com/App/lp/default (Registration required)

**Comment by lpolepeddi** [comment]
Thanks @pfms! Happy to add this to Made with Angular. Could you attach a 1280x711 screenshot of this app after someone logs in?
