### ISSUE TITLE
https://www.payjunction.com

### ISSUE THREAD

**Issue by rmodos** [lpolepeddi/made-with-angular#157]
Payment processing software.

**Comment by rmodos** [comment]
![image](https://cloud.githubusercontent.com/assets/1068669/16123031/4f386df6-339e-11e6-9af4-623dbed77a72.png)

**Comment by lpolepeddi** [comment]
@rmodos Cool! Could you send a screenshot of just the page, not the chrome?

**Comment by veintin** [comment]
Cool!
