### ISSUE TITLE
https://apps.facebook.com/blockdgame

### ISSUE THREAD

**Issue by javier-lerones-gallego** [lpolepeddi/made-with-angular#217]
A cute puzzle game for facebook made with Angular v4.

![blockd-level11](https://user-images.githubusercontent.com/5751787/28694024-69ce9aea-72dc-11e7-9fd9-19687ccdf28e.png)

**Comment by lpolepeddi** [comment]
@javier-lerones-gallego Thanks! Blockd is up on Made with Angular - https://www.madewithangular.com/sites/blockd
