### ISSUE TITLE
www.actimore.com

### ISSUE THREAD

**Issue by filipmartinsson** [lpolepeddi/made-with-angular#219]
Actimore helps you find fun group activities to do in Stockholm, Sweden.

![image](https://user-images.githubusercontent.com/10158281/29210955-82d4ae88-7e96-11e7-9049-9191502d81f1.png)

![image](https://user-images.githubusercontent.com/10158281/29210978-996cc8a6-7e96-11e7-9339-83f78f636433.png)

**Comment by lpolepeddi** [comment]
@filipmartinsson Thanks! Actimore is up on Made with Angular - https://www.madewithangular.com/sites/actimore
