### ISSUE TITLE
https://github.com/TheoKand/AngularJS-Tetris

### ISSUE THREAD

**Issue by TheoKand** [lpolepeddi/made-with-angular#223]
An original AngularJS version of the most popular video game ever.

https://github.com/TheoKand/AngularJS-Tetris

demo:
http://angulartetris20170918013407.azurewebsites.net/AngularJS-App/

**Comment by lpolepeddi** [comment]
@TheoKand thanks! AngularJS Tetris is up on Made with Angular - https://www.madewithangular.com/sites/angularjs-tetris
