### ISSUE TITLE
https://kanceliarineparduotuve.lt/

### ISSUE THREAD

**Issue by ErikasKontenis** [lpolepeddi/made-with-angular#225]
There is the e-shop solution built with AngularJs. However, its content is not in English but maybe for show-off purposes this is not a big deal :)

**Comment by lpolepeddi** [comment]
@ErikasKontenis Thanks! Your site is up on Made with Angular - https://www.madewithangular.com/sites/kanceliarine-parduotuve

Sorry for my delay in getting to this issue!
