### ISSUE TITLE
Can I get name change for bizns Tool CRM

### ISSUE THREAD

**Issue by Babugoli** [lpolepeddi/made-with-angular#227]
Sorry for bothering for change, we are changed our software construction industry

Can you please change name 

Bizns Tool CRM 

to 

Bizns Tool - Construction Software for Subcontractors.

really appreciate it

**Comment by lpolepeddi** [comment]
https://github.com/lpolepeddi/made-with-angular/blob/master/projects.json#L6508-L6511 -
 Updated `name` to be the domain name, and updated `desc` to be the site description.
