### ISSUE TITLE
https://showcase-it.firebaseapp.com

### ISSUE THREAD

**Issue by tsebvaan** [lpolepeddi/made-with-angular#233]
ShowcaseIT is a web app for showcasing apps(website/web app, android apps, desktop apps), sharing source codes, and distributing apps to other users.

Built with Angular 4, Ionic 3 and Firebase

**Comment by lpolepeddi** [comment]
@tsebvaan Thanks! ShowcaseIT is up on Made with Angular - https://www.madewithangular.com/sites/showcaseit
