### ISSUE TITLE
http://morenodd.com

### ISSUE THREAD

**Issue by MorenoDD** [lpolepeddi/made-with-angular#234]
It's my personal portfilo's website.

<img width="2555" alt="schermata 2017-12-05 alle 15 23 47" src="https://user-images.githubusercontent.com/501663/33613250-6d624a80-d9d4-11e7-95b7-3b0e476258b6.png">

**Comment by lpolepeddi** [comment]
@MorenoDD Thanks! Your portfolio site is up on Made with Angular - https://www.madewithangular.com/sites/moreno-di-domenico
