### ISSUE TITLE
Request to add www.fresh-trim.com

### ISSUE THREAD

**Issue by andrejwright** [lpolepeddi/made-with-angular#235]
Fresh Trim is a brand new website aimed to help people find their local barber.

You can see it here: www.fresh-trim.com

I am really proud of the site as it was my first production website in angular 4.

I would appreciate it if you could showcase it to the world.

Thanks,

André

**Comment by lpolepeddi** [comment]
@andrejwright Congratulations on the site. Fresh Trim is up on Made with Angular - https://www.madewithangular.com/sites/fresh-trim

**Comment by freshtrimapp** [comment]
Thanks very much!
