### ISSUE TITLE
https://my.questrade.com

### ISSUE THREAD

**Issue by ashwinmahesh** [lpolepeddi/made-with-angular#236]

**Comment by lpolepeddi** [comment]
@ashwinmahesh Could you attach a 1280x711 PNG screenshot of the site after someone logs in?

**Comment by ashwinmahesh** [comment]
![questrade-iq-web](https://user-images.githubusercontent.com/6790143/33719419-a3598918-db2e-11e7-8526-a195523bb1c0.png)

I dont have one in that size. does this 1473x926 image work?

**Comment by lpolepeddi** [comment]
@ashwinmahesh Thanks! Questrade is up on Made with Angular - https://www.madewithangular.com/sites/questrade
