### ISSUE TITLE
easyCast [launch your video platform with professional tools]

### ISSUE THREAD

**Issue by Crizstian** [lpolepeddi/made-with-angular#238]
![captura de pantalla 2017-12-26 a la s 12 04 31](https://user-images.githubusercontent.com/11022466/34362016-4e2aff2e-ea35-11e7-9318-64999f14ccb1.png)

**Easy and powerful**
Launch your video platform with professional tools

Easycast is a cloud-based platform that gives you the power to ingest, build, deliver and manage high performing video apps on phone, tablet and TV screens.

http://easycast.com/

**Comment by lpolepeddi** [comment]
@Crizstian Thanks! Easycast is up on Made with Angular - https://www.madewithangular.com/sites/easycast
