### ISSUE TITLE
https://www.venture.co/

### ISSUE THREAD

**Issue by Samushel** [lpolepeddi/made-with-angular#242]
Technology provider for investors.

Using Angular 5.2.0 at the moment.

![venture co](https://user-images.githubusercontent.com/14022771/35062334-fdcc3a3e-fb91-11e7-987a-9740437e8b3e.png)

**Comment by lpolepeddi** [comment]
@Samushel Thanks! Venture.co is up on Made with Angular - https://www.madewithangular.com/sites/venture-co
