### ISSUE TITLE
New made with angular sites

### ISSUE THREAD

**Issue by arjunpat** [lpolepeddi/made-with-angular#246]
I believe that Google Classroom and the new Google Calendar is made with angular.

**Comment by lpolepeddi** [comment]
On what URLs do you see Angular being used?

**Comment by arjunpat** [comment]
Classroom.google.com, calendar.google.com

**Comment by arjunpat** [comment]
I’m new to angular, so I don’t really know. But if you look at the html source code of the sites, you see a lot of ng- attributes on elements. How do you usually tell if an app is made tho angular?

**Comment by lpolepeddi** [comment]
While I see a few `ng-non-bindable` directives on both sites, it doesn't look like those sites are using Angular - unsure why those directives are there.

For AngularJS apps, when AngularJS loads it will add a global variable to the `window` object. So if you visit a site made with AngularJS (eg https://angularjs.org/), open the console, and type `window.angular`, it will return an object. For other sites, this will return `null`.

For Angular apps, when Angular loads it will create a DOM element with an `ng-version` attribute. So if you visit a site made with Angular (eg https://angular.io/), open the console, and type `document.querySelector('[ng-version]')`, it will return an object. For other sites, this will return `null`.

[This Chrome extension](https://chrome.google.com/webstore/detail/angular-inspector/odkdoekijebogaiopbjgkgogkgifjfnk) uses these two techniques to detect Angular apps as you browse.
