### ISSUE TITLE
https://www.pixm.io

### ISSUE THREAD

**Issue by jareko999** [lpolepeddi/made-with-angular#247]
<img width="1440" alt="screen shot 2018-02-14 at 9 51 27 am" src="https://user-images.githubusercontent.com/13771384/36210577-c42b38ac-116c-11e8-86f2-d373f72dda92.png">

**Comment by lpolepeddi** [comment]
@jareko999 Thanks! Pixm is up on Made with Angular - https://www.madewithangular.com/sites/pixm
