### ISSUE TITLE
https://www.friluftsland.dk/ 

### ISSUE THREAD

**Issue by jdelfs** [lpolepeddi/made-with-angular#250]
<img width="765" alt="friluftsland" src="https://user-images.githubusercontent.com/36935900/36813310-740c3d3a-1cd4-11e8-93ec-43f5ed23804a.png">

Great E-commerce site in Scandinavia.
https://www.friluftsland.dk
https://www.friluftsland.se

**Comment by lpolepeddi** [comment]
@jdelfs Thanks! Friluftsland is up on Made with Angular -
 https://www.madewithangular.com/sites/friluftsland
