### ISSUE TITLE
Crisp.chat is using Angular for its dashboard

### ISSUE THREAD

**Issue by LeCoupa** [lpolepeddi/made-with-angular#252]
The whole Crisp dashboard is built using Angular. Would be cool to add it. :-)

https://crisp.chat/en/

**Comment by lpolepeddi** [comment]
@LeCoupa Great! Could you send over a 1280x711 screenshot after someone logs in?

**Comment by LeCoupa** [comment]
Here it is! Thanks again :-)

![screenshot_inbox](https://user-images.githubusercontent.com/1658644/37006163-f4ff7640-208b-11e8-9ac1-a756574d130e.png)

**Comment by lpolepeddi** [comment]
@LeCoupa Thanks! Crisp is up on Made with Angular - https://www.madewithangular.com/sites/crisp
