### ISSUE TITLE
PPSR Cloud

### ISSUE THREAD

**Issue by zijianhuang** [lpolepeddi/made-with-angular#255]
https://ppsr.cloud

For evaluating the UI, try https://sandbox.ppsr.cloud
with VIN: JTNBU56E20J006689

Built on Angular 5 and Material 5.

A video tutorial is at https://youtu.be/6U7yEyWc0Xg

**Comment by lpolepeddi** [comment]
@zijianhuang Thanks! PPSR Cloud is up on Made with Angular - https://www.madewithangular.com/sites/ppsr-cloud
