### ISSUE TITLE
https://cloud-player.io

### ISSUE THREAD

**Issue by Zarlex** [lpolepeddi/made-with-angular#258]
[Cloud-Player](https://cloud-player.io) is an [open source](https://github.com/Cloud-Player/web) music player build with Angular 5.
With Cloud-Player you can search and play SoundCloud and YouTube tracks

![cloud-player io_ 1](https://user-images.githubusercontent.com/2241390/38488081-9418837c-3be2-11e8-919d-80eccb47885f.png)

**Comment by lpolepeddi** [comment]
@Zarlex Thanks! Cloud-Player is up on Made with Angular - https://www.madewithangular.com/sites/cloud-player
