### ISSUE TITLE
http://www.curlify.net/

### ISSUE THREAD

**Issue by zak905** [lpolepeddi/made-with-angular#263]
app for generating curl commands. Made with Angular 5. 

is this site for AngularJs only or all versions of Angular ?

**Comment by lpolepeddi** [comment]
@zak905 Thanks! Curlify is up on Made with Angular - https://www.madewithangular.com/sites/curlify

The site is showcases both [sites made with AngularJS](https://www.madewithangular.com/categories/angularjs) and [sites made with Angular](https://www.madewithangular.com/categories/angular)
