### ISSUE TITLE
Parrot: self-hosted localization management platform

### ISSUE THREAD

**Issue by anthonynsimon** [lpolepeddi/made-with-angular#267]
Hi there, not really a website per se, but our project Parrot is using Angular for the web app.

Here's the website: http://parrot-translate.github.io/parrot.github.io/

<img width="1440" alt="screen shot 2018-05-10 at 7 17 28 pm" src="https://user-images.githubusercontent.com/13251079/39883328-d44ff580-5486-11e8-812d-1358c12acb1c.png">

![image](https://user-images.githubusercontent.com/13251079/39883251-89de547e-5486-11e8-94d2-d9a0b4768cdd.png)

**Comment by lpolepeddi** [comment]
@anthonynsimon Thanks! Parrot is up on Made with Angular - https://www.madewithangular.com/sites/parrot

**Comment by anthonynsimon** [comment]
Cool thanks!
