### ISSUE TITLE
Artwork Management Services, Artwork Solutions, Life Sciences

### ISSUE THREAD

**Issue by freyrsolutions** [lpolepeddi/made-with-angular#418]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mkaram/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mkaram/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Freyr   provides Global Regulatory [Artwork Management Services](
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mkaram/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mkaram/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

https://artwork.freyrsolutions.com/
--

</body>

</html>
) &amp; Solutions   for life sciences Industry, which include Artwork proofreading, Artwork   packaging, Artwork Lifecycle management, Artwork Studio Services.
--

</body>

</html>

**Comment by lalithpolepeddi** [comment]
Similar to #417, we noticed that https://artwork.freyrsolutions.com/ has evolved away from using Angular. We'll go ahead and close this issue for the time being. If you have any new projects made with Angular, please consider [sharing them in this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432) - thank you!
