### ISSUE TITLE
booktrack.com

### ISSUE THREAD

**Issue by rixrix** [lpolepeddi/made-with-angular#84]
Hi,

Our public and education apps is built on Angular + TypeScript. We're prepping for ng2 since alpha releases

web app
- https://booktrack.com
- https://booktrackclassroom.com

chrome app (featured in chrome web store)
- https://chrome.google.com/webstore/detail/booktrack-classroom/odmndfiaonleilpbajajkijoihjemocc?utm_source=chrome-app-launcher
- https://chrome.google.com/webstore/detail/booktrack-studio/kidknbkmfcapkiepmhchinffchkjglog?utm_source=chrome-app-launcher

mobile app (android)
- https://play.google.com/store/apps/details?id=com.booktrack.gelada&hl=en
- https://play.google.com/store/apps/details?id=com.booktrack.gelada.edu&hl=en

mobile app (ios)
- https://itunes.apple.com/us/app/booktrack-reader/id836391798?mt=8
- https://itunes.apple.com/us/app/classroom-reader/id847896655?mt=8

**Comment by lpolepeddi** [comment]
Cool! Could you send me a 1280x711 JPEG screenshot of your app?
